add support for monitoring LVM caches (Closes: #158)
prometheus-community/node-exporter-textfile-collector-scripts pull request #159
Opened 2023-06-06 22:18 UTC by anarcat

This is basically a copy-paste of the snapshots code, and seems to work on my end.

2023-06-08 10:37 UTC, SuperQ requested changes
Can you rebase this with the `-a` flag and include a `display_usage()` update?

2023-06-08 18:34 UTC, anarcat commented
this has been rebased on top of #161 and #160 (master).

2023-10-11 19:20 UTC, anarcat commented
@SuperQ ping

2026-04-20 14:16 UTC, anarcat commented
@SuperQ i can't seem to be able to tell github that your "requested changes" have been answered here, i rerolled on top of master too.

2026-04-20 14:21 UTC, SuperQ approved these changes
Thanks

2026-04-20 14:21 UTC, merged