Added script to collect mailq metrics
prometheus-community/node-exporter-textfile-collector-scripts pull request #59
Opened 2020-07-20 13:06 UTC by tguentel

2020-07-20 13:08 UTC, dswarbrick commented
Have you considered using https://github.com/kumina/postfix_exporter (assuming your mail system is postfix)?

2020-07-20 13:16 UTC, tguentel commented
Yes, I did. But I dont need so many data. Makes no sense in my case to rollout, run an maintain a separate exporter on all my hosts, when I just want to know, if there is a growing mailq.

2021-01-05 22:33 UTC, hansmi requested changes

2021-01-05 22:33 UTC, hansmi commented on mailq.sh
> +# * -1 means mailq command is not found
What @SuperQ is getting at is that you shouldn't export -1/-2 as metrics values for failures, but instead let the script fail. Something like this:

```
#!/bin/bash

set -e -u -o pipefail

count=$(mailq | grep -c '^[A-F0-9]')

echo '# HELP mailq_size_total Count of e-mails in MTA queue'
echo '# TYPE mailq_size_total gauge'
echo "mailq_size_total=${count}"
```

Note that `set -e` causes the shell to automatically fail if a command fails, e.g. in a variable assignment (try this in an interactive shell: `foo=$(false); echo $?`). [`set -o pipefail` is to get the first non-zero exit code in pipelines](https://www.gnu.org/software/bash/manual/html_node/Pipelines).

2021-01-05 22:33 UTC, hansmi commented on mailq.sh
> +if [ "$MAILQCMD" != "" ]
Just for future reference: [Bash sets the status to 127 for unavailable commands](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html).

2023-05-23 19:06 UTC, dswarbrick commented
@tguentel Please address the outstanding suggestions if you still wish to submit this.

2023-07-12 12:06 UTC, closed without merging

2023-07-13 07:48 UTC, frittentheke commented
@tguentel  Did you want to close this? Just asking since you did push a new commit just before the close.